/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import type { Item, Table } from 'airtable-ts';

export interface Storie extends Item {
  id: string,
  identifier: string | null,
  headline: string,
  shortDescription: string,
  longArticle: string,
  authors: string[],
  authorsName: string | null,
  status: string,
  newsletters: string[],
  happenings: string[],
  autonumber: number,
}

export const storiesTable: Table<Storie> = {
  name: 'stories',
  baseId: 'appF6DPjeUnTXYQ7c',
  tableId: 'tblVumB36qqSGeRyA',
  mappings: {
    identifier: 'fldJ4gyuCFPMqCKih',
    headline: 'fldx4W1IM6vAq808d',
    shortDescription: 'fldK57l5jenrW86jH',
    longArticle: 'fldBRu20Ep4jRdEFe',
    authors: 'fldmGCoGZiUc3Kq2j',
    authorsName: 'fldIFwkwqXec0GQEf',
    status: 'fldcJLMlsn4undLnw',
    newsletters: 'fldQcfErFDTa4FW1F',
    happenings: 'fldLCaN8QESZQYbPK',
    autonumber: 'fldFT2rDBipeHUnAc',
  },
  schema: {
    identifier: 'string | null',
    headline: 'string',
    shortDescription: 'string',
    longArticle: 'string',
    authors: 'string[]',
    authorsName: 'string | null',
    status: 'string',
    newsletters: 'string[]',
    happenings: 'string[]',
    autonumber: 'number',
  },
};

export interface Reporter extends Item {
  id: string,
  identifier: string | null,
  bio: string,
  stories: string[],
  firstName: string,
  lastName: string,
  fullName: string | null,
  autonumber: number,
  slackId: string,
}

export const reportersTable: Table<Reporter> = {
  name: 'reporters',
  baseId: 'appF6DPjeUnTXYQ7c',
  tableId: 'tblsvsF0yqBtMDOEX',
  mappings: {
    identifier: 'fldUQ0GvSU8qJvTxL',
    bio: 'fldMXWuVzVOVc2e10',
    stories: 'fld8miYxySZF1PJdg',
    firstName: 'fldzLyipkX3cxGBf1',
    lastName: 'fldc0hLW45728kkjV',
    fullName: 'fldpLd6AGjn2AcRL6',
    autonumber: 'fldG7dXqPSYY01bdu',
    slackId: 'fldycxMMVYU9uHB0h',
  },
  schema: {
    identifier: 'string | null',
    bio: 'string',
    stories: 'string[]',
    firstName: 'string',
    lastName: 'string',
    fullName: 'string | null',
    autonumber: 'number',
    slackId: 'string',
  },
};

export interface Newsletter extends Item {
  id: string,
  identifier: string | null,
  stories: string[],
  publicationDate: number,
  publicationDateString: string | null,
  autonumber: number,
}

export const newslettersTable: Table<Newsletter> = {
  name: 'newsletters',
  baseId: 'appF6DPjeUnTXYQ7c',
  tableId: 'tbllAabfaqxzdSgm2',
  mappings: {
    identifier: 'fldbEUAeF956tDLZC',
    stories: 'fldbG39lvOCAyZzNm',
    publicationDate: 'fldOECtNvfLtTcxdn',
    publicationDateString: 'flddNr7khK1HqSG8H',
    autonumber: 'fldLYDXJiqsTMxJPD',
  },
  schema: {
    identifier: 'string | null',
    stories: 'string[]',
    publicationDate: 'number',
    publicationDateString: 'string | null',
    autonumber: 'number',
  },
};

export interface Happening extends Item {
  id: string,
  identifier: string | null,
  stories: string[],
  publicationDate: number,
  publicationDateString: string | null,
  autonumber: number,
}

export const happeningsTable: Table<Happening> = {
  name: 'happenings',
  baseId: 'appF6DPjeUnTXYQ7c',
  tableId: 'tbleyNcpeztuGXgE1',
  mappings: {
    identifier: 'fldxqrkAE0YzLb1bm',
    stories: 'fldfZ19PnoIIC5dPT',
    publicationDate: 'fldPXXeYvIQ8AIvuy',
    publicationDateString: 'fldBxjZrZm3kVSmPq',
    autonumber: 'fldnuVtPaMUwRtW8h',
  },
  schema: {
    identifier: 'string | null',
    stories: 'string[]',
    publicationDate: 'number',
    publicationDateString: 'string | null',
    autonumber: 'number',
  },
};